version: '3'

services:
  web:
    restart: always
    build: ./web
    hostname: simhash-web
    environment:
      - TZ=Asia/Taipei
    ports:
      - "5000:5000"
    container_name: simhash-web
    command: bash -c "uwsgi --ini uwsgi.ini"
    logging:
      driver: json-file
      options:
        max-size: 50m

  nginx:
    restart: always
    image: nginx
    container_name: simhash-nginx
    environment:
      - TZ=Asia/Taipei
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443
    logging:
      driver: json-file
      options:
        max-size: 50m
    depends_on:
      - web

networks:
  net: